version: '3'
services:
  github-backup:
    image: akrck02/github-backup:latest
    container_name: github-backup
    restart: always
    environment:
      - GITHUB_REFRESH_INTERVAL=${GITHUB_REFRESH_INTERVAL}
      - GITHUB_BACKUP_USER=${GITHUB_BACKUP_USER}
      - GITHUB_BACKUP_TOKEN=${GITHUB_BACKUP_TOKEN}
      - GITHUB_BACKUP_PATH=${GITHUB_BACKUP_PATH}
      - GITHUB_FETCH_USERNAMES=${GITHUB_FETCH_USERNAMES}
      - GITHUB_FETCH_TOKEN=${GITHUB_FETCH_TOKEN}
      - GITHUB_FETCH_JSON_PATH=${GITHUB_FETCH_JSON_PATH}